Controller dev
ldncode/SQA pull request #2
Opened 2020-05-13 14:08 UTC by ldncode

2020-05-13 15:54 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.save
а если условие не выполняется, что тогда?

2020-05-13 15:55 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to render_template
какой шаблон должен рендериться?

2020-05-13 15:55 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { post :create, params: { question_id: question, answer: attributes_for(:answer, :invalid) } }.to_not change(question.answers, :count)
здесь в change стоит поставитиь просто Answer, т.к. важно, что в принципе ответ не создан, вне зависомсти от его связей

2020-05-14 15:40 UTC, ldncode commented on app/controllers/answers_controller.rb
> +    if @answer.save
Исправил

2020-05-26 14:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def new
new для ответов не нужен, т.к. форма на странице вопроса

2020-05-26 14:00 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render :new
раз форма на странице вопроса, то ее (страницу вопроса) и надо рендерить (questions/show)

2020-05-26 14:01 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +class AnswersController < ApplicationController
В задании есть история про удаление ответов. Где реализация удаления?

2020-05-26 14:01 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +class QuestionsController < ApplicationController
Также в задании есть и история про удаление вопросов. Но реализации нет

2020-05-26 14:01 UTC, vkurennov commented on app/views/answers/_form.html.slim
> += form_with model: [@question, @answer], local: true do |f|
нужен вывод ошибок валидации

2020-05-26 14:02 UTC, vkurennov commented on app/views/questions/_form.html.slim
> += form_with model: @question do |f|
добавь тут опцию `local: true`, а то может быть неправильное поведение. эта опция будет объяснена в след. уроке

2020-05-26 14:03 UTC, vkurennov commented on app/views/questions/index.html.slim
> +     td= q.title
а как перейти на конкретный вопрос, если это не ссылка, а просто текст?

2020-05-26 14:04 UTC, vkurennov commented on spec/features/answer/answer_create_spec.rb
> +feature 'User can create answer to question', %q{
нужны сценарии для невалидного ответа и для незалогиненного пользователя

2020-05-26 14:05 UTC, vkurennov commented on spec/features/question/create_spec.rb
> +feature 'User can create questions', %q{
смотри, вот эта фича была реализована в уроке, тут 3 сценария. проведи аналогию с фичей создания ответов

2020-05-26 14:05 UTC, vkurennov commented on spec/features/question/show_questions_spec.rb
> +  scenario 'view question' do
тут надо проверить список ответов еще, то, что он на странице вопроса виден

2020-05-26 14:06 UTC, vkurennov commented on spec/features/sign_in_spec.rb
> +feature 'User can sing out', %q{
каждая фича должна быть в отдельном файле

2020-07-24 08:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def new
не исправлено, new не нужен

2020-07-24 08:51 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +class AnswersController < ApplicationController
не исправлено, удаления по-прежнему нет

2020-07-24 08:52 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question.destroy
тут нужна проверка на автора, даже если она есть в видах, т.к. а)по условию задачи, только автор может удалить вопрос и б) легко сделать прямой запрос, в обход вида, и удалить чужой вопрос (в текущей реализации)

2020-07-24 08:53 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def create
у тебя не устанавливается связь между вопросом и ответом, а т.к. ассоциации belongs_to являются обязательными, то вопрос тут всегда невалидный. и по идее, у тебя должны не проходить тесты контроллера на создание валидного вопроса

2020-07-24 08:53 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def create
тут нужно связывать ответ и пользователя (автора), который его создал

2020-07-24 08:54 UTC, vkurennov commented on app/views/questions/index.html.slim
> +     td= q.title
не исправлено

2020-07-24 08:54 UTC, vkurennov commented on app/views/questions/new.html.slim
> += render 'shared/errors', resource: @question
это лучше сразу в паршл формы перенести

2020-07-24 08:55 UTC, vkurennov commented on app/views/questions/show.html.slim
> += link_to 'Delete', question_path, method: :delete
зачем показывать ссылку на удаление всем? добавь здесь условие и показывай только автору вопроса.
ну и сама ссылка неверная, т.к. надо объект передавать в question_path: `question_path(@question)`

2020-07-24 08:56 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      td= q.body
как удалять ответы? (см истории из 3го блока в задании)

2020-07-24 08:57 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
тут нужно проверить, что созданный вопрос связывается с залогиненным юзером (и то же самое и в контроллере ответов для ответа)

2020-07-24 08:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe 'DELETE #destroy' do
тут должно быть 2 условия: автор удаляет вопрос и не-автор

2020-07-24 08:58 UTC, vkurennov commented on spec/features/answer/answer_create_spec.rb
> +feature 'User can create answer to question', %q{
не исправлено

2020-07-24 08:58 UTC, vkurennov commented on spec/features/question/delete_questions_spec.rb
> +  scenario 'Non author can not delete question'
где реализация этого сценария?

2020-07-24 08:59 UTC, vkurennov commented on spec/features/question/delete_questions_spec.rb
> +    click_on 'Delete'
лучше не показывать ссылку на удаление и это и проверить

2020-07-24 08:59 UTC, vkurennov commented on spec/features/sign_in_spec.rb
> +feature 'User can sing out', %q{
не исправлено

2020-07-24 08:59 UTC, vkurennov commented on spec/models/user_spec.rb
> +  it { is_expected.to validate_presence_of :email }
в тестах, также как и в самих моделях, сначала идут ассоциации, потом валидации, потом уже остальные методы

2020-08-06 08:10 UTC, ldncode commented on app/views/questions/index.html.slim
> +     td= q.title
Исправлено

2020-08-06 08:10 UTC, ldncode commented on app/views/questions/_form.html.slim
> += form_with model: @question do |f|
+

2020-08-06 08:10 UTC, ldncode commented on app/views/questions/_form.html.slim
> += form_with model: @question do |f|
Ок

2020-08-06 12:24 UTC, ldncode commented on spec/features/sign_in_spec.rb
> +feature 'User can sing out', %q{
Ok

2020-08-18 09:00 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - @question.answers.each do |q|
чтобы не возникало путаницы в какой переменной что лежит, давай осмысленные имена, тут лучше бы в блоке переменную назвать `answer`, ну или в крайнем случае `a` (но лучше полное имя давать), сразу было бы ясно, где лежит ответ и какую переменную использовать в блоке

2020-08-18 09:01 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
вот  тут нужен еще тест, проверяющий, что ответ связывается с залогиненным юзером. для этого надо после запроса через assigns получить созданный ответ и сравнить у него юзера с юзером, который логинится в 7й строке

2020-08-18 09:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to change(question.answers, :count).by(-1)
здесь в change первым аргументом лучше поставить Answer, т.к. важно проверить что ответ в целом удалился, а его ассоциации тут не важны

2020-08-18 09:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to_not change(question.answers, :count)
тут тоже просто Answer в change

2020-08-18 09:02 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to question_path
question_path должен принимать аргумент - вопрос, на который ведет путь

2020-08-18 09:03 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
вот этот комментарий не исправлен до сих пор: тут нужно проверить, что созданный вопрос связывается с залогиненным юзером

2020-08-18 09:05 UTC, vkurennov commented on spec/features/answer/answer_create_spec.rb
> +    scenario 'An unauthenticated user tries to create an answer' do
это фактически тот же самый сценарий, что и выше, причем, ты в предыдущем уже проверил сообщение. а нужны еще 2 сценария: на невалидный ответ, проверить, что ошибки выводятся и для незалогиненного юзера, что он не может создать ответ (не видит формы, например)

2020-08-18 09:05 UTC, vkurennov commented on spec/features/answer/delete_answers_spec.rb
> +    expect(page).to have_content 'Answer deleted'
еще надо проверить, что текста ответа нет на странице

2020-08-18 09:06 UTC, vkurennov commented on spec/features/question/show_questions_spec.rb
> +  scenario 'view question' do
тут  надо проверить, что виден список ответов на странице вопроса

2020-08-18 09:07 UTC, vkurennov commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
тут теперь есть ассоциация с юзером, надо покрыть это тестом.  и у вопроса тоже

2020-08-18 13:49 UTC, ldncode commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to change(question.answers, :count).by(-1)
Исправил

2020-08-18 13:49 UTC, ldncode commented on spec/controllers/answers_controller_spec.rb
> +        expect { delete :destroy, params: { id: answer } }.to_not change(question.answers, :count)
Исправил

2020-08-18 14:15 UTC, ldncode commented on spec/models/answer_spec.rb
>  RSpec.describe Answer, type: :model do
Добавил

2020-08-18 14:28 UTC, ldncode commented on spec/features/question/show_questions_spec.rb
> +  scenario 'view question' do
Добавил

2020-08-19 05:49 UTC, ldncode commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
Исправил

2020-08-19 06:04 UTC, ldncode commented on spec/features/answer/delete_answers_spec.rb
> +    expect(page).to have_content 'Answer deleted'
Исправил

2020-08-19 09:39 UTC, vkurennov requested changes

2020-08-19 09:39 UTC, vkurennov commented on app/models/user.rb
> +  def author_of?(answer)
тут ведь в качестве аргумента может быть и вопрос и вообще любой объект, не только ответ. поэтому лучше дать более общее имя для аргумента, например, resource или item

2020-08-19 09:39 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user == @question.user
тут тоже надо применить вызов метода `author_of?`

2020-08-19 09:39 UTC, vkurennov commented on app/views/questions/show.html.slim
> +       -if current_user == answer.user
тут тоже надо применить вызов метода `author_of?`

2020-08-19 09:39 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    context 'with valid attributes' do
что исправил? где этот тест? у тебя как было тут 2 теста, так и осталось. а должен добавиться еще один.

2020-08-19 09:39 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(response).to redirect_to question_path
не исправлено. обрати внимание на 45ю строку, вот и тут также должно быть

2020-08-19 09:39 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    context 'with valid attributes' do
так и нет теста на свзяь вопроса и залогиненного юзера. как и с ответами, здесь должно быть всего 3 теста, два есть, нужен еще один

2020-08-19 09:39 UTC, vkurennov commented on spec/features/answer/answer_create_spec.rb
> +  I would like to be able to create an answer to the question
тут нужен сценарий для невалидого ответа

2020-08-19 09:39 UTC, vkurennov commented on spec/features/answer/delete_answers_spec.rb
> +    expect(page).to_not have_content 'answer.body'
это неверная проверка, ты саму строку 'answer.body' проверяешь, понятно, что такого текста нет на странице. а надо проверять то, что возвращает answer.body, т.е. без кавычек

2020-08-19 09:39 UTC, vkurennov commented on spec/features/question/show_questions_spec.rb
> +  scenario 'view question' do
что добавил? нет у тебя здесь такого сценария. вообще ничего про проверку списка ответов нет, а должно быть, об этом и был комментарий

2020-08-20 09:20 UTC, vkurennov approved these changes

2020-08-20 09:32 UTC, merged